config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'home#index'
  devise_for :project_owners, path: 'project_owners'
  devise_for :freelancers, path: 'freelancers'

  resources :projects, only: %i[index new create show] do
    resources :freelancers do
      resources :freelancer_feedbacks, only: %i[new create show]
    end

    resources :proposals, only: %i[show create] do
      post 'accept', on: :member
      post 'reject', on: :member
      post 'cancel', on: :member

      resources :proposal_cancelations, only: %i[new create]
    end

    get 'my_projects', on: :collection
    post 'finish', on: :member
  end

  resources :profiles, only: %i[show edit update] do
    resources :freelancers_favorites, only: %i[create destroy]
  end

  get 'search', to: 'projects#search'
  get 'my_proposals', to: 'proposals#my_proposals'
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :freelancer
  belongs_to :occupation_area, optional: true
  has_one_attached :avatar

  validates :full_name, :birth_date, :description, :occupation_area, presence: true, on: :update
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :completed_profile?, except: %i[create edit update]
  before_action :authenticate_person!, only: [:show]
  before_action :authenticate_freelancer!, except: [:show]

  def show
    @profile = Profile.find(params[:id])
  end

  def edit
    @profile = Profile.find(params[:id])
    @occupation_area = OccupationArea.all
  end

  def update
    @profile = Profile.find(params[:id])
    @occupation_area = OccupationArea.all

    @profile.avatar.attach(params[:avatar]) if params[:avatar].present?

    if @profile.update(profile_params)
      redirect_to @profile
    else
      render :edit
    end
  end

  private

  def profile_params
    params.require(:profile).permit(:full_name, :social_name, :birth_date, :description, :occupation_area_id, :avatar)
  end

  def authenticate_person!
    return if freelancer_signed_in? || project_owner_signed_in?

    redirect_to root_path
  end
end

app/views/profiles/edit.html.erb
<div class="container shadow p-3 mt-5 bg-body rounded col-4">
  <h1 class="text-center">Meu Perfil</h1>

  <%= form_with(model: @profile) do |f| %>
    <div>
      <%= f.label :full_name, class:"form-label" %>
      <% @profile.errors.full_messages_for(:full_name).each do |message| %>
        <div><%= message %></div>
      <% end %>
      <%= f.text_field :full_name, class:"form-control" %>
    </div>
      <div>
      <%= f.label :social_name %>
      <% @profile.errors.full_messages_for(:social_name).each do |message| %>
        <div><%= message %></div>
      <% end %>
      <%= f.text_field :social_name, class:"form-control"  %>
    </div>
    <div>
      <%= f.label :description %>
      <% @profile.errors.full_messages_for(:description).each do |message| %>
        <div><%= message %></div>
      <% end %>
      <%= f.text_area :description, class:"form-control", rows: 5 %>
    </div>
    <div>
      <%= f.label :birth_date %>
      <% @profile.errors.full_messages_for(:birth_date).each do |message| %>
        <div><%= message %></div>
      <% end %>
      <%= f.date_field :birth_date, class:"form-control" %>
    </div>
    <div>
      <%= f.label :occupation_area_id, 'Área de Atuação' %>
      <% @profile.errors.full_messages_for(:occupation_area).each do |message| %>
        <div><%= message %></div>
      <% end %>
          <%= f.collection_select :occupation_area_id, @occupation_area, :id, :name, {:prompt => 'Selecione uma área de atuação'}, class:"form-select" %>
    </div>
    <div>
      <%= f.label :avatar, class:"form-label" %>
      <%= f.file_field :avatar, class:"form-control" %>
      <% @profile.errors.full_messages_for(:avatar).each do |message| %>
            <div><%= message %></div>
      <% end %>
    </div>
    <%= f.submit 'Salvar Perfil', class:"btn btn-primary mt-3 form-control" %>
  <% end %>
</div>

app/views/profiles/show.html.erb
<div class="container shadow p-3 mt-5 bg-body rounded col-4">
    <% if freelancer_signed_in? && @profile.freelancer == current_freelancer%>
        <div class="text-center">
            <h1 class="text-center d-inline">Meu Perfil</h1>
            <% if @profile.avatar.present?%>
                <%= image_tag @profile.avatar, alt: "avatar-profile", :size => "100x100", class:"img-fluid img-thumbnail" %>
            <% end %>
        </div>
 
    <% else %>
        <h1>Perfil de <%= @profile.social_name%></h1>
        <% if project_owner_signed_in? && @profile.freelancer.freelancer_favorites.where("freelancer_id = ? AND project_owner_id = ?", @profile.freelancer.id, current_project_owner.id).present? %>
            <h3>Freelancer Favorito</h3>
        <% end %>
    <% end %>



    <div>
    Nome Completo: <%= @profile.full_name %>

    </div>


    <div>
    Nome Social: <%= @profile.social_name %>
    </div>

    <div>
    Data de Nascimento: <%= I18n.l(@profile.birth_date) %>
    </div>

    <div>
    Área de Atuação: <%= @profile.occupation_area.name %>
    </div>

    <div>
    Descrição: <%= @profile.description %>
    </div>

    <% if project_owner_signed_in? && @profile.freelancer.freelancer_favorites.where("freelancer_id = ? AND project_owner_id = ?", @profile.freelancer.id, current_project_owner.id).present? %>
        <%= link_to 'Retirar dos Favoritos', profile_freelancers_favorite_path(@profile, @profile.freelancer.freelancer_favorites.where("freelancer_id = ? AND project_owner_id = ?", @profile.freelancer.id, current_project_owner.id)[0].id), method: :delete %> 
    <% elsif project_owner_signed_in?  %>
        <%= link_to 'Favoritar', profile_freelancers_favorites_path(@profile), method: :post %>
    <% end %>

    <% if freelancer_signed_in? && @profile.freelancer == current_freelancer%>
        <%= link_to 'Editar', edit_profile_path, class: 'btn btn-primary mt-3 form-control' %>
    <% end %>
</div>