config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'home#index'
  devise_for :project_owners, path: 'project_owners'
  devise_for :freelancers, path: 'freelancers'

  resources :projects, only: %i[index new create show] do
    resources :freelancers do
      resources :freelancer_feedbacks, only: %i[new create show]
    end

    resources :proposals, only: %i[show create] do
      post 'accept', on: :member
      post 'reject', on: :member
      post 'cancel', on: :member

      resources :proposal_cancelations, only: %i[new create]
    end

    get 'my_projects', on: :collection
    post 'finish', on: :member
  end

  resources :profiles, only: %i[show edit update] do
    resources :freelancers_favorites, only: %i[create destroy]
  end

  get 'search', to: 'projects#search'
  get 'my_proposals', to: 'proposals#my_proposals'
end

app/views/shared/_footer.html.erb
<footer class="bg-light text-center fixed-bottom pb-2 pt-2">
    &#169; <%= link_to "Caio Sant'Ana da Silva", 'https://github.com/caiosant', :target => '_blank', class: 'text-dark text-decoration-none' %> & 
           <%= link_to 'TreinaDev', 'https://treinadev.com.br/', :target => '_blank', class: 'text-dark text-decoration-none'  %>
</footer>

app/views/shared/_header.html.erb
<header class=''>
    <nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="<%= root_path %>">Freelancer-TD7</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <% if freelancer_signed_in? %>
                        <li class="nav-item"><%= link_to 'Projetos Disponíveis', projects_path, class: "nav-link active"%></li>
                        <li class="nav-item"><%= link_to 'Meus Projetos', my_projects_projects_path, class: "nav-link active" %></li>
                        <li class="nav-item"><%= link_to 'Minhas Propostas', my_proposals_path, class: "nav-link active" %></li>
                        <li class="nav-item"><%= link_to current_freelancer.email, profile_path(current_freelancer.profile.id), class: "nav-link active" %></li>
                        <li class="nav-item"><%= link_to 'Logout', destroy_freelancer_session_path, method: 'delete', class: "nav-link active"%></li>
                <% elsif project_owner_signed_in?  %>
                        <li class="nav-item"> <%= link_to 'Cadastrar Projeto', new_project_path, class: "nav-link active" %> </li>
                        <li class="nav-item"> <%= link_to 'Meus Projetos', my_projects_projects_path, class: "nav-link active" %> </li>
                        <li class="nav-item"> <%= link_to "Usuário: #{current_project_owner.email}", edit_project_owner_registration_path(), class: "nav-link active" %> </li>
                        <li class="nav-item"> <%= link_to 'Logout', destroy_project_owner_session_path, method: 'delete', class: "nav-link active"%> </li>
            <% end %>
      </ul>
      
      <% if freelancer_signed_in? %>
        <%= form_with url: search_path, class:"d-flex", method: :get do %>
            <%= text_field_tag :q, nil, placeholder:"Procurar Projeto", class:"form-control me-2"  %>
            <%= submit_tag 'Pesquisar', class:"btn btn-outline-success" %>
        <% end %>
      <% end %>
    </div>
  </div>
</nav>

</header>