config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'home#index'
  devise_for :project_owners, path: 'project_owners'
  devise_for :freelancers, path: 'freelancers'

  resources :projects, only: %i[index new create show] do
    resources :freelancers do
      resources :freelancer_feedbacks, only: %i[new create show]
    end

    resources :proposals, only: %i[show create] do
      post 'accept', on: :member
      post 'reject', on: :member
      post 'cancel', on: :member

      resources :proposal_cancelations, only: %i[new create]
    end

    get 'my_projects', on: :collection
    post 'finish', on: :member
  end

  resources :profiles, only: %i[show edit update] do
    resources :freelancers_favorites, only: %i[create destroy]
  end

  get 'search', to: 'projects#search'
  get 'my_proposals', to: 'proposals#my_proposals'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :completed_profile?
end

app/views/home/index.html.erb
<% unless freelancer_signed_in? || project_owner_signed_in? %>
    
    <main class="text-center" style="display: grid; place-content: center;">
        <h2 style="margin-top:2rem">O que deseja fazer?</h2>

        <ul class="list-inline d-flex flex-wrap", style="gap: 1rem;">
            <li>
                <%= link_to 'Oferecer Projetos', new_project_owner_session_path, class: "btn btn-secondary" %> 
            </li>
            <li>
                <%= link_to 'Entrar em Projetos', new_freelancer_session_path, class: "btn btn-secondary" %>
            </li>
        </ul>
    </main>
<% end %>