config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'home#index'
  devise_for :project_owners, path: 'project_owners'
  devise_for :freelancers, path: 'freelancers'

  resources :projects, only: %i[index new create show] do
    resources :freelancers do
      resources :freelancer_feedbacks, only: %i[new create show]
    end

    resources :proposals, only: %i[show create] do
      post 'accept', on: :member
      post 'reject', on: :member
      post 'cancel', on: :member

      resources :proposal_cancelations, only: %i[new create]
    end

    get 'my_projects', on: :collection
    post 'finish', on: :member
  end

  resources :profiles, only: %i[show edit update] do
    resources :freelancers_favorites, only: %i[create destroy]
  end

  get 'search', to: 'projects#search'
  get 'my_proposals', to: 'proposals#my_proposals'
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :project_owner
  has_many :proposals
  has_many :project_abilities
  has_many :abilities, through: :project_abilities
  has_many :project_cancelations, through: :proposal
  has_many :freelancer_feedbacks
  has_many :freelancers, through: :freelancer_feedbacks

  validates :title, :description, :max_value, :deadline, :location, presence: true
  validates :description, length: { minimum: 30 }
  validates :max_value, numericality: { greater_than: 0 }
  validate :deadline_is_possible?
  validate :has_ability?

  enum location: { remotely: 5, local: 10 }
  enum project_application: { open: 5, closed: 10 }
  enum project_status: { started: 5, finished: 10 }

  def deadline_is_possible?
    return if deadline.blank?

    errors.add(:deadline, 'precisa maior ou igual a hoje') if Date.current > deadline
  end

  def self.my_project?(project, project_owner)
    return false if project_owner.blank?

    project.project_owner_id == project_owner.id
  end

  def has_ability?
    errors.add(:abilities, 'precisa ter ao mínimo uma opção selecionada') if abilities.blank?
  end

  def self.location_attributes_for_select
    locations.map do |location, _|
      [I18n.t("activerecord.attributes.#{model_name.i18n_key}.locations.#{location}"), location]
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :completed_profile?
  before_action :authenticate_project_owner!, only: %i[new create]

  def index
    @projects = Project.all
  end

  def show
    if Project.my_project?(Project.find(params[:id]), current_project_owner) || !current_freelancer.nil?
      @project = Project.find(params[:id])
      @proposal = Proposal.new
    else
      redirect_to root_path
    end
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    @project.project_owner = current_project_owner

    if @project.save
      redirect_to @project
    else
      render :new
    end
  end

  def my_projects
    if !current_project_owner.nil?
      @projects = current_project_owner.projects
    elsif !current_freelancer.nil?
      @proposals = current_freelancer.proposals
    end
  end

  def finish
    if Project.my_project?(Project.find(params[:id]), current_project_owner)
      @project = Project.find(params[:id])
      @project.finished!
      redirect_to @project
    end
  end

  def search
    if current_freelancer.nil?
      redirect_to root_path
    else
     @projects = Project.where('title like ? OR description like ?', "%#{params[:q]}%", "%#{params[:q]}%")
    end
  end

  private

  def project_params
    params.require(:project).permit(:title, :description, :max_value,
                                    :deadline, :location, ability_ids: [])
  end
end

app/views/projects/index.html.erb
<h1 class="text-center">Projetos Disponívels</h1>

<% if @projects.empty?%>
    <div>
        Não existem projetos disponíveis no momento
    </div>
<% end %>

<%= render "projects/shared/projects_cards"%>

app/views/projects/my_projects.html.erb
<h1>Meus Projetos</h1>

<% if project_owner_signed_in? %>
    <% if @projects.empty? %>
        <div>
            <h3>Você não tem projetos cadastrados.</h3><br>
        </div>
        <div>
            <%= link_to 'Clique aqui para criar o seu primeiro projeto!', new_project_path %>
        </div>
    <% end %>
<% elsif freelancer_signed_in? %>
    <% if @proposals.empty? %>
        <div>
            <h3>Você ainda não tem propostas aceitas.</h3><br>
        </div>
    <% end %>
<% end %>

<% if project_owner_signed_in? %>
    <% @projects.each do |project|%>
        <li>Projeto: <%= link_to project.title, project %></li>
        <li>Data Limite para Propostas: <%= I18n.l(project.deadline) %></li>
    <% end %>
<% elsif freelancer_signed_in? %>
    <% @proposals.where(proposal_status: 'accepted').each do |proposal|%>
        <li>Projeto: <%= link_to proposal.project.title, proposal.project %></li>
        <li>Data Limite para Propostas: <%= I18n.l(proposal.project.deadline) %></li>
    <% end %>
<% end %>

app/views/projects/new.html.erb
<div class="container shadow p-3 mt-5 bg-body rounded col-4">
  <%= form_with(model: @project) do |f| %>
    <div>
      <%= f.label :title, class:"form-label" %>
      <% @project.errors.full_messages_for(:title).each do |message| %>
        <div><%= message %></div>
      <% end %>
      <%= f.text_field :title, class:"form-control" %>
    </div>
    <div>
      <%= f.label :description, class:"form-label" %>
      <% @project.errors.full_messages_for(:description).each do |message| %>
        <div><%= message %></div>
      <% end %>
      <%= f.text_area :description, class:"form-control", rows: 5 %>
    </div>
    <div>
      <%= f.label :max_value, class:"form-label" %>
      <% @project.errors.full_messages_for(:max_value).each do |message| %>
        <div><%= message %></div>
      <% end %>
      <%= f.number_field :max_value, class:"form-control" %>
    </div>
    <div class="form-check">
      <%= f.label :abilities, class: "form-check-label" %><br>
      <% @project.errors.full_messages_for(:abilities).each do |message| %>
        <div><%= message %></div>
      <% end %>
      <%= f.collection_check_boxes :ability_ids, Ability.all, :id, :name, class: "form-check-input"%>
    </div>
    <div>
      <%= f.label :deadline, class:"form-label" %>
      <% @project.errors.full_messages_for(:deadline).each do |message| %>
        <div><%= message %></div>
      <% end %>
      <%= f.date_field :deadline, class:"form-control" %>
    </div>
    <div>
      <%= f.label :location, class:"form-label" %>
      <% @project.errors.full_messages_for(:location).each do |message| %>
        <div><%= message %></div>
      <% end %>
      <%= f.select :location, options_for_select(Project.location_attributes_for_select), {include_blank: 'Selecione uma Opção'}, class:"form-select" %>
    </div>

    <%= f.submit 'Cadastar Projeto', class:"btn btn-primary mt-3 form-control" %>
  <% end %>
</div>

app/views/projects/search.html.erb
<h1>Projetos Disponívels</h1>

<% if @projects.empty?%>
    <div>
        Não existem projetos disponíveis no momento
    </div>
<% end %>
   
<%= render "projects/shared/projects_cards"%>

app/views/projects/show.html.erb
<div class="container shadow p-3 my-5 bg-body rounded col-4">
   <ul class="list-group">
      <li class="list-group-item"> 
         <div class="text-center fs-5 fw-bold">
            Projeto
         </div>   
         <%= @project.title %>
      </li>
      <li class="list-group-item"> 
         <div class="text-center fs-5 fw-bold">
            Descrição
         </div>   
         <%= @project.description %>
      </li>
      <li class="list-group-item"> 
         <div class="text-center fs-5 fw-bold">
            Valor Máximo por Hora
         </div>   
         <%= number_to_currency @project.max_value %>
      </li>
      <li class="list-group-item"> 
         <div class="text-center fs-5 fw-bold">
            Data Limite para Propostas
         </div>   
         <%= I18n.l(@project.deadline) %>
      </li>
      <li class="list-group-item"> 
         <div class="text-center fs-5 fw-bold">
            Habilidade(s)
         </div>   
         <% @project.abilities.each do |ability| %>
            <%= ability.name %>
         <% end %>
      </li>
      <li class="list-group-item"> 
         <div class="text-center fs-5 fw-bold">
            Forma de trabalho
         </div>   
         <%= Project.human_enum_name(:locations, @project.location) %>
      </li>
      <li class="list-group-item"> 
         <div class="text-center fs-5 fw-bold">
            Status do Projeto
         </div>
         <%= I18n.t(@project.project_status) %>
      </li>
   
      <% if (project_owner_signed_in? && @project.project_owner == current_project_owner && @project.proposals.where(proposal_status: 'accepted').empty?) || ( freelancer_signed_in? && @project.proposals.where(proposal_status: 'accepted').empty?) %>
               <li class="list-group-item">
                  <div class="text-center fs-5 fw-bold">
                     Time do Projeto
                  </div> 
                  Ainda não existem propostas aceitas
               </li>
      <% elsif (project_owner_signed_in? && @project.project_owner == current_project_owner) || (freelancer_signed_in? && @project.proposals.where("proposal_status = ? AND freelancer_id = ?", "accepted", current_freelancer.id)) %>
            <div>
               <div>
                  Time do Projeto:
               </div>
               <div>
                  <% @project.proposals.where(proposal_status: 'accepted').each do |proposal| %>
                     <div>
                        <%= link_to proposal.freelancer.profile.social_name, proposal.freelancer.profile %>
                        <% if (project_owner_signed_in? && @project.project_owner == current_project_owner && @project.project_status == 'finished' && @project.freelancer_feedbacks.where('freelancer_id = ?', proposal.freelancer.id).present?) %>
                           <div>
                              Feedback já realizado
                           </div>
                        <% else %>
                           <%= link_to 'Realizar Feedback', new_project_freelancer_freelancer_feedback_path(@project.id, proposal.freelancer.id) %>
                        <% end %>
                     </div>
                  <% end %>
               </div>
            </div>
      <% end %>
   </ul>


   <% if project_owner_signed_in? && @project.project_owner == current_project_owner && @project.project_status != 'finished'%>
      <%= link_to 'Finalizar Projeto', finish_project_path, method: 'post' %>
   <% end %>

   <% if freelancer_signed_in? && current_freelancer.projects.include?(@project)%>
      <div>
         Você já enviou proposta para este projeto, clique aqui, para ver ela.
      </div>
   <% elsif project_owner_signed_in? && @project.project_owner == current_project_owner %>
      <h3>Propostas:</h3>
      <% if @project.proposals.where(proposal_status: 'pending').empty? %>
         <div>
            Não existem propostas para serem avaliadas neste momento.
         </div>
      <% else %>
         <% @project.proposals.where(proposal_status: 'pending').each do |proposal|%>
            <li>Freelancer: <%=link_to proposal.freelancer.profile.social_name, proposal.freelancer.profile %></li>
            <li>Valor por hora: <%= number_to_currency proposal.hour_value %></li>
            <li>Previsão de entrega: <%= I18n.l(proposal.deadline_proposal) %>
            <li>Status da Proposta: <%= I18n.t(proposal.proposal_status) %></li>
            <li id=<%= "proposal_#{proposal.id}" %>><%= link_to 'Visualizar Proposta Completa', project_proposal_path(proposal.id) %>
            <div id=<%= "accept_proposal_#{proposal.id}" %>><%= link_to 'Aceitar Proposta', accept_project_proposal_path(proposal.id), method: :post, class:"btn btn-success mt-3" %></li>
            <div id=<%= "reject_proposal_#{proposal.id}" %>><%= link_to 'Rejeitar Proposta', reject_project_proposal_path(proposal.id), method: :post, class:"btn btn-danger mt-3" %></li>
         <% end %>
      <% end %>
   <% else %>
      <%= render "projects/shared/proposal_apply"%>
   <% end %>
</div>